.\"
.\"  This program is free software; you can redistribute it and/or modify
.\"  it under the terms of the GNU General Public License as published by
.\"  the Free Software Foundation; either version 2 of the License, or
.\"  (at your option) any later version.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"
.\"  You should have received a copy of the GNU General Public License along
.\"  with this program; if not, write to the Free Software Foundation, Inc.,
.\"  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"

.TH PCB 1

.SH NAME
.B pcb
\- Printed circuit board layout tool

.SH SYNOPSIS
.B pcb [options] [pcb file]

.SH DESCRIPTION
The
.B pcb
program is a tool for the layout of printed circuit boards.
The complete manual for
.B pcb
is provided in a GNU texinfo format as well as HTML and PDF.
The texinfo version of the manual is typically viewed with the
.B info
program or alternatively with 
.B emacs
or a graphical info viewer such as
.B tkinfo.
The PDF and HTML documentation is typically installed as
/usr/local/share/pcb/pcb.html and /usr/local/share/pcb/pcb.pdf.
The prefix "/usr/local" may vary at your site.




