#!/bin/sh
#

CONVERT=${CONVERT:-convert}
INKSCAPE=${INKSCAPE:-inkscape}
PPMTOWINICON=${PPMTOWINICON:-ppmtowinicon}

##
## Export the SVG graphics
##

echo "Export SVG graphics to png..."

# see if we have inkscape
do_inkscape=yes
${INKSCAPE} --version 2>&1 >/dev/null
if test $? -ne 0 ; then
	echo "\"${INKSCAPE} --version\" failed.
	echo "Make sure that inkscape is installed and functional on your system."
	echo "Skipping the SVG -> PNG conversion."
	do_inkscape=no
fi

if test $do_inkscape = yes ; then
	for r in 16 22 24 32 48 ; do
		for f in *-${r}.svg ; do
			fb=`basename ${f} .svg`
			p="${fb}.png"
			echo "${f} -> ${p}"
			${INKSCAPE} --export-png=${p} --export-area=0:0:${r}:${r}
		done
	done
fi

##
## Generate the windows icon file
##

echo "Creating windows ppm files..."

app_icon="application-x-pcb-layout"

${CONVERT} -colors 16 ${app_icon}-48.png 48_16.ppm
${CONVERT} -colors 256 ${app_icon}-48.png 48_256.ppm
${CONVERT} -colors 16 ${app_icon}-32.png 32_16.ppm
${CONVERT} -colors 256 ${app_icon}-32.png 32_256.ppm
${CONVERT} -colors 16 ${app_icon}-16.png 16_16.ppm
${CONVERT} -colors 256 ${app_icon}-16.png 16_256.ppm

echo "Creating windows icon file..."
${PPMTOWINICON} -output pcb_icon.ico \
    48_16.ppm 48_256.ppm \
    32_16.ppm 32_256.ppm \
    16_16.ppm 16_256.ppm

rm \
    48_16.ppm 48_256.ppm \
    32_16.ppm 32_256.ppm \
    16_16.ppm 16_256.ppm

