\input texinfo    @c -*-texinfo-*-
@comment %**start of header
@setfilename gs.info
@settitle Getting Started With PCB
@setcontentsaftertitlepage
@comment %**end of header

@include ../version.texi

@comment This macro defines how we present the name of the pcb project.
@comment Use @code{pcb} for the name of the executable, @pcb{} for the project.
@macro pcb
@sc{pcb}
@end macro

@ifinfo
@format
INFO-DIR-SECTION Miscellaneous
START-INFO-DIR-ENTRY
* pcb: (pcb).                   An interactive printed circuit board editor.
END-INFO-DIR-ENTRY
@end format
@end ifinfo

@iftex
@finalout
@end iftex

@ifinfo

This file documents how to get started using @pcb{}, the interactive
printed circuit board layout system.

Copyright (C) 2007 DJ Delorie

This program is free software; you may redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANT-ABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the @b{GNU
General Public License} for more details.

@end ifinfo

@setchapternewpage on
@headings single

@tex
\def\lastnegativepageno{\pageno}
\def\savepageno{\pageno}
@end tex

@titlepage
@title Getting Started With @pcb{}
@author DJ Delorie
@end titlepage

@tex
\global\advance\pageno by 2
@end tex

@contents

@ifnottex
@node Top
@top Getting Started with PCB

This document is a manual for @pcb{}, the interactive printed
circuit board layout system.

@menu
* Introduction::   Introduction to @pcb{}
* Terminology::    Terms and definitions.
* Installation::
* Your First Board::
@end menu

@end ifnottex

@comment our type of image
@macro img{INAME}
@center @image{\INAME\}
@end macro

@macro press{TXT}
@kbd{\TXT\}
@end macro

@iftex
@tex
\gdef\rarrow{$\rightarrow$}
@end tex
@end iftex
@ifhtml
@macro rarrow
@html
&rarr;
@end html
@end macro
@end ifhtml
@ifnottex
@ifnothtml
@macro rarrow
->
@end macro
@end ifnothtml
@end ifnottex

@macro mnu{TXT}
@b{\TXT\}
@end macro

@macro mnuu{T1,T2}
@b{\T1\@rarrow{}\T2\}
@end macro


@macro mnuuu{T1,T2,T3}
@b{\T1\@rarrow{}\T2\@rarrow{}\T3\}
@end macro

@c -----------------------------------------------------------------------------
@c Each node herein will be moved to its own file when it's filled in.

@include introduction.texi
@include terminology.texi
@include installation.texi
@include firstboard.texi

@bye
