#! /bin/sh

usage ()
{
  echo Usage: 
  echo \\tpcbdiff firstfile secondfile
  echo \\tView a graphical diff of PCB files
  echo
  echo \\tTo use with git, just place this script in your PATH and do
  echo \\tgit difftool -x pcbdiff ...
  echo
  echo \\tTo use with mercurial, add the following lines to your .hgrc:
  echo \\t\\t[extensions]
  echo \\t\\thgext.extdiff =
  echo \\t\\t[extdiff]
  echo \\t\\tcmd.pcbdiff = /PATH/TO/pcbdiff
  echo \\tthen to invoke it, do
  echo \\thg pcbdiff ...
  echo
  echo \\tTo use with subversion, place it in your PATH and do
  echo \\tsvn diff --diff-cmd pcbdiff ...

  echo \\tRequirements: Imagemagick and gschem be installed
}


for PROG in pcb convert composite
do
  if which $PROG > /dev/null
  then 
    true
  else 
    echo "$PROG is not found.  Either it is not installed, or not in your PATH"
    exit 1
  fi
done

#In case the script was invoked with extra option arguments, throw them away
shift `expr $# - 2`

if test -d $1 -o -d $2
  then echo "ERROR: pcbdiff cannot diff entire directories"
  exit 1
fi

LEFTFILE=$1
RIGHTFILE=$2
LEFTPNG=`mktemp --tmpdir pcbdiff.XXXXXXXXXX`
RIGHTPNG=`mktemp --tmpdir pcbdiff.XXXXXXXXXX`
LEFTBNW=`mktemp --tmpdir pcbdiff.XXXXXXXXXX`
RIGHTBNW=`mktemp --tmpdir pcbdiff.XXXXXXXXXX`
DIFFPNG=`mktemp --tmpdir pcbdiff.XXXXXXXXXX`

pcb -x png --dpi 200 --only-visible --photo-mode --outfile $LEFTPNG $LEFTFILE
pcb -x png --dpi 200 --only-visible --photo-mode --outfile $RIGHTPNG $RIGHTFILE
convert -colorspace gray $LEFTPNG $LEFTBNW
convert -colorspace gray $RIGHTPNG $RIGHTBNW
composite -stereo 0 $LEFTBNW $RIGHTBNW $DIFFPNG
display $DIFFPNG
rm $LEFTPNG
rm $RIGHTPNG
rm $LEFTBNW
rm $RIGHTBNW
rm $DIFFPNG
